name: Chrome

on: [push]

jobs:
   cypress-ct:
      runs-on: ubuntu-latest
      env:
         CYPRESS_RETRIES: 2
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: '20'
         - uses: pnpm/action-setup@v2
           name: Install pnpm
           id: pnpm-install
           with:
              version: 8
              run_install: false
         - name: Install dependencies
           run: pnpm install
         - name: Window scroll
           run: pnpm -C packages/vue-use-fixed-header run test:chrome
         - name: Custom scrolling container
           run: pnpm -C packages/vue-use-fixed-header test:container:chrome
